version: '2.0'

services:

    db_mysql:
        container_name: mysql-802
        build: ./setup/mysql
        image: mysql-802
        command: --default-authentication-plugin=mysql_native_password
        volumes:
<<<<<<< HEAD
            - /config/mysql:/etc/mysql/conf.d
            - /data/mysql:/var/lib/mysql
=======
            - ./data/mariadb:/var/lib/mysql # enable on linux
            - ./config/mariadb_extra.cnf:/etc/my.cnf.d/mariadb_extra.cnf
>>>>>>> 30906b525707e4110379c0260d8e9a72dabb082b
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 112143

    cache_memcached:
        container_name: memcached-16
        build: ./setup/memcached
        image: memcached-16
        restart: always
        ports:
            - 11211:11211

    php_apache:
        container_name: apache-24-php-73
        build: ./setup/php-apache
        image: apache-24-php-73
        volumes:
            - ./html:/var/www/html
            - ./config/php_php.ini:/usr/local/etc/php/php.ini
            - ./config/apache2_000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./log/apache2:/var/log/apache2
        ports:
            - 80:80
        depends_on:
            - db_mysql
        links:
            - db_mysql
            - cache_memcached
            - cache_redis

    # cache_redis:
    #     container_name: redis-603
    #     build: ./setup/redis
    #     image: redis-603
    #     restart: always
    #     environment:
    #         - ALLOW_EMPTY_PASSWORD=yes
    #         - REDIS_PASSWORD=secret
    #     command: /opt/bitnami/scripts/redis/run.sh --maxmemory 256mb
    #     ports:
    #         - 6379:6379

    # db_adminer:
    #     container_name: adminer-47
    #     build: ./setup/adminer
    #     image: adminer-47
    #     volumes:
    #         - ./config/adminer_0-upload_large_dumps.ini:/usr/local/etc/php/conf.d/0-upload_large_dumps.ini
    #     restart: always
    #     ports:
    #         - 8000:8080
    #     depends_on:
    #         - db_mysql

    db_phpmyadmin:
        container_name: phpmyadmin-5
        build: ./setup/phpmyadmin
        image: phpmyadmin-5
        volumes:
            - ./config/phpmyadmin_php.ini:/opt/bitnami/php/etc/php.ini
        restart: always
        ports:
            - 8001:80
        environment:
            - DATABASE_HOST=db_mysql
            - DATABASE_PORT_NUMBER=3306
        depends_on:
            - db_mysql
        links:
            - db_mysql
