version: '2.4'

services:

    db_mariadb:
        container_name: mariadb-104
        build: ./setup/mariadb
        image: mariadb-104
        volumes:
            # - ./data/mariadb:/var/lib/mysql # enable on linux
            - ./config/mariadb_extra.cnf:/etc/my.cnf.d/mariadb_extra.cnf
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 112143

    php_apache:
        container_name: apache-24-php-73
        build: ./setup/php-apache
        image: apache-24-php-73
        volumes:
            - ./html:/var/www/html
            - ./config/php_php.ini:/usr/local/etc/php/php.ini
            - ./config/apache2_000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./log/apache2:/var/log/apache2
        ports:
            - 80:80
        depends_on:
            - db_mariadb
        links:
            - db_mariadb
            - cache_memcached
            - cache_redis

    cache_memcached:
        container_name: memcached-16
        build: ./setup/memcached
        image: memcached-16
        restart: always
        ports:
            - 11211:11211

    cache_redis:
        container_name: redis-603
        build: ./setup/redis
        image: redis-603
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_PASSWORD=secret
        command: /opt/bitnami/scripts/redis/run.sh --maxmemory 256mb
        ports:
            - 6379:6379

    db_adminer:
        container_name: adminer-47
        build: ./setup/adminer
        image: adminer-47
        volumes:
            - ./config/adminer_0-upload_large_dumps.ini:/usr/local/etc/php/conf.d/0-upload_large_dumps.ini
        restart: always
        ports:
            - 8000:8080
        depends_on:
            - db_mariadb

    db_phpmyadmin:
        container_name: phpmyadmin-5
        build: ./setup/phpmyadmin
        image: phpmyadmin-5
        volumes:
            - ./config/phpmyadmin_php.ini:/opt/bitnami/php/etc/php.ini
        restart: always
        ports:
            - 8001:80
        environment:
            - DATABASE_HOST=db_mariadb
            - DATABASE_PORT_NUMBER=3306
        depends_on:
            - db_mariadb
        links:
            - db_mariadb