version: '3.1'
services:

    db_mariadb:
        image: yobasystems/alpine-mariadb:10.4.13
        restart: always
        ports:
            - 33333:3306
        environment:
            MYSQL_ROOT_PASSWORD: 112143

    php_apache:
        build: setup/php
        volumes:
            - ./www:/var/www/html
        ports:
            - 80:80
        depends_on:
            - db_mariadb
        links:
            - db_mariadb
            - cache_memcached

    cache_memcached:
        image: memcached:1.6.6-alpine
        restart: always
        ports:
            - 22222:11211

    db_adminer:
        image: adminer:4.7.7-standalone
        restart: always
        ports:
            - 11111:8080
        depends_on:
            - db_mariadb