version: '3.1'
services:

    db_mariadb:
        container_name: MariaDB-10.4
        image: yobasystems/alpine-mariadb:10.4.13
        restart: always
        ports:
            - 33333:3306
        environment:
            MYSQL_ROOT_PASSWORD: 112143

    php_apache:
        container_name: PHP-7.3-Apache-2.4
        build: setup/php
        volumes:
            - ./www:/var/www/html
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
            - ./log/apache2_access.log:/var/log/apache2/access.log
            - ./log/apache2_error.log:/var/log/apache2/error.log
        ports:
            - 80:80
            - 443:443
        depends_on:
            - db_mariadb
        links:
            - db_mariadb
            - cache_memcached

    cache_memcached:
        container_name: Memcached-1.6
        image: memcached:1.6.6-alpine
        restart: always
        ports:
            - 22222:11211

    db_adminer:
        container_name: Adminer-4.7
        image: adminer:4.7.7-standalone
        restart: always
        ports:
            - 11111:8080
        depends_on:
            - db_mariadb